name: Statistician
main: com.ChaseHQ.Statistician.StatisticianPlugin
version: ${project.version}
description: Extremely detailed player/server statistic tracking with web portal.
website: http://dev.bukkit.org/server-mods/statisticianv2/
author: ChaseHQ
authors: [Coryf88]
softdepend:
    - Spout
permissions:
  statistician.ignore:
    description: Don't record statistics of the player.
    default: false